### PR TITLE
fix for missing ports variable.

### PR DESCRIPTION
**Pull request by samowitsch**
I have tried to install an run grblweb on my raspberry pi with an protoneer cnc shield. The ports variable is not defined, a javascript runtime error occurs?

### CODE REVIEW

**Comment by andrewhodel** [comment]
It's a better fix to use the native tty module - https://nodejs.org/api/tty.html

Here's some code:

```
 16 // open sp as tty
 17 fs.open('/dev/ttyUSB0', 'r', function(err, fd) {
 18         var s = new tty.ReadStream(fd);
 19 
 20         var nl = '';
 21 
 22         s.on('data', function (data) {
 23                 data = data.toString();
 24 
 25                 if (data == '\n') {
 26                         handle serial output(nl);
 27                         nl = '';
 28                 } else {
 29                         nl += data;
 30                 }
 31         });
 32 });
```

**Comment by samowitsch** [comment]
I have fixed some points with my little javascript knowledge. nodejs i have never used/programmed before. If you have a proper solution then implement it ;-)

**Comment by simook** [comment]
I just encountered this while configuring my bananapro with grblweb. It's currently not hooked up to my cnc, but I should at the very minimum be able to run the server without encountering errors.

**Comment by andrewhodel** [comment]
Post the node version, the contents of node_modules and the actual output of the program. 


Thanks,
Andrew

**Comment by itpmngt** [comment]
Hi

This happens because Serial port wasn't selected and server'js is trying to do a 'soft reset' on the serial (that wasn't selected)

It happens at line '261'

I've added an if block to check if it is selected:

		if (sp[currentSocketPort[socket.id]] ){
			sp[currentSocketPort[socket.id]].handle.write("\030");
			// reset vars
			sp[currentSocketPort[socket.id]].q = [];
			sp[currentSocketPort[socket.id]].qCurrentMax = 0;
			sp[currentSocketPort[socket.id]].lastSerialWrite = [];
			sp[currentSocketPort[socket.id]].lastSerialRealLine = '';
		}

Best,

**Comment by samowitsch** [comment]
No one is interested. I close this pull request.

**Pull request closed without merging**
